package com.inventiapp.stocktrack.inventory.domain.model.valueobject;

/**
 * Lifecycle status of an expiration alert raised against a batch.
 * <p>
 * PENDING: alert generated by the daily scan and awaiting a mitigation action.
 * RESOLVED: a mitigation action (liquidation/return) has been registered for the alert.
 * <p>
 * Alerts are only moved out of PENDING by an explicit action (US17 part 2); there is no
 * automatic expiry, so an untouched alert simply stays PENDING.
 */
public enum AlertStatus {
    PENDING,
    RESOLVED
}
